project_manager/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "manager"
urlpatterns = [
    path(
        "",
        views.LandingPage.as_view(),
        name="landingPage",
    ),
    path(
        "projects/",
        views.ProjectListPage.as_view(),
        name="projectList",
    ),
    path(
        "project/<int:pk>/",
        views.ProjectDetailPage.as_view(),
        name="projectDetail",
    ),
    path("propose/", views.ProjectProposalPage.as_view(), name="projectProposal"),
    path(
        "project/<int:pk>/apply/",
        views.ProjectApplicationPage.as_view(),
        name="projectApplication",
    ),
    path(
        "project/<int:pk>/edit/",
        views.ProjectEditPage.as_view(),
        name="projectEdit",
    ),
    path(
        "project/<int:pk>/delete/",
        views.ProjectDeleteView.as_view(),
        name="projectDelete",
    ),
    path(
        "advisors/",
        views.AdvisorListPage.as_view(),
        name="advisorList",
    ),
    path("advisors/<int:pk>/", views.AdvisorDetailPage.as_view(), name="advisorDetail"),
    path(
        "project/<int:pk>/applications/",
        views.ProjectApplicationListView.as_view(),
        name="projectApplications",
    ),
    path(
        "application/<int:pk>/",
        views.ProjectApplicationDetailView.as_view(),
        name="applicationDetail",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senior_project_manager/urls.py
from django.contrib import admin
from django.urls import include ,path

urlpatterns = [
    path('', include("projects.urls")),
    path('admin/', admin.site.urls),
]

project_manager/models.py
from django.db import models

# from django.db.models.enums import Choices
from django.conf import settings

# from django.forms import ImageField
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser

# from django.core.exceptions import ValidationError

from .managers import CustomUserManager


class Skill(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class User(AbstractUser):
    # Which campus user is located in.
    class Campus(models.TextChoices):
        BROWNSVILLE = "brownsville", "Brownsville"
        EDINBRUG = "edinburg", "Edinburg"

    # What type of user: students and advisor
    class UserTypes(models.TextChoices):
        STUDENT = "student", "Student"
        ADVISOR = "advisor", "Advisor"

    username = None
    email = models.EmailField(_("email"), unique=True)
    # make unique identifier into the email
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    user_type = models.CharField(
        max_length=15, choices=UserTypes, default=UserTypes.STUDENT
    )
    campus = models.CharField(max_length=15, choices=Campus, default=Campus.BROWNSVILLE)
    bio = models.TextField(blank=True)
    skills = models.ManyToManyField("Skill", blank=True)

    objects = CustomUserManager()  # pyright: ignore

    def __str__(self):
        return self.email


# Any additional advisor exclusive information
class AdvisorProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")
    courses_taught = models.TextField()
    title = models.CharField(max_length=40)

    def get_full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def __str__(self):
        return self.user.email


class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return self.user.email


class Project(models.Model):
    class Meta:
        # Permissions:
        # https://docs.djangoproject.com/en/5.2/topics/auth/default/#programmatically-creating-permissions
        # https://www.youtube.com/watch?v=AR5hjQ8nla0 |> Django Permissions | Model Level | Views and Templates
        # https://docs.djangoproject.com/en/5.2/topics/auth/default/#proxy-models
        # Custom permission for proposing projects into the database:
        permissions = (("can_propose_project", "Can Propose Project"),)

    # https://docs.djangoproject.com/en/5.2/ref/models/fields/#enumeration-types
    class Statuses(models.TextChoices):
        PENDING = "pending", "Pending"
        IN_PROGRESS = "in_progress", "In Progress"
        ARCHIVED = "archived", "Archived"
        TRASH = "trash", "Trash"

    title = models.CharField(max_length=40)
    description = models.TextField()
    status = models.CharField(max_length=15, choices=Statuses, default=Statuses.PENDING)
    created_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="created_project",
    )
    member_limit = models.IntegerField(
        choices=[(2, "2"), (3, "3"), (4, "4")], default=4  # Only allow 2, 3, or 4
    )
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="project_memberships",
        limit_choices_to={"user_type": User.UserTypes.STUDENT},
        blank=True,
    )
    advisor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="advised_projects",
        limit_choices_to={"user_type": User.UserTypes.ADVISOR},
    )
    skills_required = models.ManyToManyField(Skill, blank=True)

    @property
    def applicants(self):
        return User.objects.filter(project_applications__project=self)

    # For cli purposes
    def __str__(self):
        return self.title


class ProjectApplication(models.Model):
    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, related_name="applications"
    )
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="project_applications",
        limit_choices_to={"user_type": User.UserTypes.STUDENT},
    )
    message = models.TextField(help_text="Tell us why you'd like to join this project")
    applied_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("project", "applicant")
        ordering = ["-applied_at"]

    def __str__(self):
        return f"Application by {self.applicant.email} to {self.project.title}"


# This is a way to allow the user to have the ability to favorite a project :^D.
class Favorite(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="favorites"
    )
    project = models.ForeignKey(
        "Project", on_delete=models.CASCADE, related_name="favorites"
    )

    class Meta:
        unique_together = ("user", "project")

    def __str__(self):
        return f"{self.user} favorite {self.project}"


# https://testdriven.io/blog/django-custom-user-model/

project_manager/forms.py
from django import forms
from .models import Project, Skill, ProjectApplication
from django_select2.forms import Select2TagWidget


# https://docs.djangoproject.com/en/5.2/topics/forms/
class ProjectForm(forms.ModelForm):
    # https://docs.djangoproject.com/en/5.1/topics/forms/modelforms/#modelform
    class Meta:
        model = Project
        fields = ["title", "description", "skills_required", "member_limit"]
        skills = forms.ModelMultipleChoiceField(
            queryset=Skill.objects.all(),
            widget=forms.SelectMultiple(
                attrs={
                    "class": "select is-multiple has-background-light has-text-black",
                    "style": "background-color: #d3d3d3; border: none; font-weight: bold; max-width: 400px;",
                    "size": "6",  # Controls the visible height of the box
                }
            ),
            required=False,
        )
        # fields = "__all__"
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "input is-large has-background-light has-text-black",
                    "placeholder": "Project Title",
                    "style": "background-color: #d3d3d3; border: none; font-weight: bold;",
                    "required": True,
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "textarea has-background-light has-text-black",
                    "placeholder": "Description",
                    "style": "background-color: #d3d3d3; border: none; font-weight: bold; min-height: 240px;",
                    "required": True,
                }
            ),
            "member_limit": forms.Select(
                attrs={
                    "class": "select is-custom has-background-light has-text-black",
                    "style": "background-color: #d3d3d3; border: none; font-weight: bold;",
                }
            ),
            "skills_required": forms.SelectMultiple(
                attrs={
                    "class": "select is-multiple has-background-light has-text-black",
                    "style": "background-color: #d3d3d3; border: none; font-weight: bold; max-width: 400px;",
                    "size": "5",  # Number of visible options
                }
            ),
        }


class ApplicationForm(forms.ModelForm):
    # https://docs.djangoproject.com/en/5.1/topics/forms/modelforms/#modelform
    class Meta:
        model = ProjectApplication
        fields = ["message"]
        widgets = {
            "message": forms.Textarea(
                attrs={
                    "class": "textarea has-background-light has-text-black",
                    "placeholder": "Why do you want to join this project?",
                    "style": "min-height: 200px; background-color: #d3d3d3; border: none; font-weight: bold;",
                }
            )
        }


# title = forms.CharField(label="Project Title", max_length=40)
# date = forms.DateTimeField(widget=forms.TextInput(attrs={"type": "datetime-local"}))
# description = forms.CharField(widget=forms.Textarea())
# status = forms.ChoiceField(choices=Project.Statuses.choices)

project_manager/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Case, IntegerField, Value, When
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views import View, generic

from .forms import ApplicationForm, ProjectForm
from .models import Project, ProjectApplication, AdvisorProfile, User
from django.contrib.auth import get_user_model

User = get_user_model()
# We're using class-based views.
# https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/


class LandingPage(LoginRequiredMixin, generic.TemplateView):
    login_url = "accounts/login"
    template_name = "project_manager/landingPage.html"


class ProjectListPage(LoginRequiredMixin, generic.ListView):
    login_url = "accounts/login"
    template_name = "project_manager/projectListPage.html"
    context_object_name = "pending_projects_list"

    def get_queryset(self):
        """Return the list of pubdate"""
        return (
            Project.objects.filter(status="pending")
            .annotate(
                # Order by user creations first:
                is_mine=Case(
                    When(created_by=self.request.user, then=Value(0)),
                    default=Value(1),
                    output_field=IntegerField(),
                )
            )
            .order_by("is_mine", "-created_date")
        )


class ProjectDetailPage(LoginRequiredMixin, generic.DetailView):
    login_url = "accounts/login"
    model = Project
    template_name = "project_manager/projectDetailPage.html"


class ProjectEditPage(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "project_manager/projectEditPage.html"

    def get_success_url(self):
        return reverse("manager:projectDetail", args=[self.object.id])


class ProjectProposalPage(LoginRequiredMixin, View):
    login_url = "accounts/login"
    form_class = ProjectForm
    template_name = "project_manager/projectProposalPage.html"

    # GET form template :^D
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    # POST form to db :^D
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.created_by = request.user
            project = form.save()
            return redirect(reverse("manager:projectDetail", args=[project.id]))
        return render(request, self.template_name, {"form": form})


class ProjectDeleteView(generic.DeleteView):
    model = Project
    template_name = "project_manager/project_confirm_delete.html"
    success_url = reverse_lazy("manager:projectList")


class ProjectApplicationPage(LoginRequiredMixin, generic.FormView):
    form_class = ApplicationForm
    template_name = "project_manager/projectApplicationPage.html"

    def get_project(self):
        return get_object_or_404(Project, pk=self.kwargs["pk"])

    def get(self, request, *args, **kwargs):
        project = self.get_project()
        form = self.get_form()
        return self.render_to_response(
            self.get_context_data(form=form, project=project)
        )

    def form_valid(self, form):
        project = self.get_project()
        applicant = self.request.user
        message = form.cleaned_data["message"]

        # Create the application
        application = ProjectApplication.objects.create(
            project=project, applicant=applicant, message=message
        )

        # Redirect to the project detail page aftera the user applies
        return HttpResponseRedirect(reverse("manager:projectDetail", args=[project.id]))

    def form_invalid(self, form):
        project = self.get_project()
        return self.render_to_response(
            self.get_context_data(form=form, project=project)
        )


class AdvisorListPage(LoginRequiredMixin, generic.ListView):
    login_url = "accounts/login"
    template_name = "project_manager/advisorListPage.html"
    context_object_name = "advisors_list"

    def get_queryset(self):
        """Return the list of pubdate"""
        return User.objects.filter(user_type=User.UserTypes.ADVISOR).select_related(
            "advisorprofile"
        )


class AdvisorDetailPage(generic.DetailView):
    model = AdvisorProfile
    template_name = "project_manager/advisorDetailPage.html"
    context_object_name = "advisor"


class ProjectApplicationListView(LoginRequiredMixin, generic.ListView):
    model = ProjectApplication
    template_name = "project_manager/projectApplicationList.html"
    context_object_name = "applications"

    def get_queryset(self):
        project = get_object_or_404(Project, pk=self.kwargs["pk"])
        if project.created_by != self.request.user:
            raise PermissionDenied
        return ProjectApplication.objects.filter(project=project)


class ProjectApplicationDetailView(LoginRequiredMixin, generic.DetailView):
    model = ProjectApplication
    template_name = "project_manager/projectApplicationDetailView.html"
    context_object_name = "application"

    def get_object(self):
        application = super().get_object()
        if application.project.created_by != self.request.user:
            raise PermissionDenied("You are not allowed to view this application.")
        return application

    def post(self, request, *args, **kwargs):
        application = self.get_object()

        if "admit" in request.POST:
            project = application.project
            if project.members.count() < project.member_limit:
                project.members.add(application.applicant)
                application.delete()
            else:
                return redirect("manager:projectDetail", pk=project.pk)

        elif "discard" in request.POST:
            application.delete()
        return redirect("manager:projectDetail", pk=application.project.pk)

project_manager/templates/project_manager/advisorDetailPage.html
{% extends "project_manager/base.html" %}

{% block content %}

<section class="section" style="padding-top: 60px;">
  <div class="container">
    <a href="{% url 'manager:advisorList' %}" class="button is-light mb-5">
      ← Back to Advisor List
    </a>

    <div class="advisor-profile">
      <div class="columns is-vcentered">

        <div class="column is-3 has-text-centered">
          <h1 class="title">{{ advisor.get_full_name }}</h1>

          <figure class="image">
            <img src="{{ advisor.image.url }}" alt="{{ advisor.get_full_name }}">
          </figure>

          <h4 class="title is-4">{{ advisor.title }}</h4>
          <p class="mt-1">
            <a href="mailto:{{ advisor.user.email }}" class="has-text-link">
                {{ advisor.user.email }}
            </a>
          </p>
        </div>

        <div class="column">
          <h5 class="title is-5"> Biography </h5>
          <hr class="my-4">
          <p class="is-size-5 mb-5">
            {{ advisor.user.bio }}

          </p>
          <hr class="my-4">
          <div class=columns>
          <div class="column">
          <h5 class="title is-5"> Courses Taught</h5>
          <p class="is-size-5 mb-5">
            {{ advisor.courses_taught }}
          </p>
          </div>
          <div class="column">
          <h5 class="title is-5"> Skills </h5>
          {% for skill in advisor.user.skills.all %}
            <li>{{ skill.name }}</li>
          {% empty %}
            <li>No skills listed</li>
          {% endfor %}
          </div>
        </div>

    {% if role == "Admin" %}
    <div class="button-container">
      <a href="/admin/projects/advisor/{{ advisor.id }}/change/" class="button is-medium is-gray roboto-font">
        Edit Profile
      </a>
    </div>
    {% endif %}
  </div>
</section>
{% endblock %}

project_manager/templates/project_manager/advisorListPage.html
{% extends "project_manager/base.html" %}

{% block content %}
{% load static %}
<h2>Advisors List</h2>

    <a href="{% url 'manager:landingPage' %}" class="button is-light mb-5">
      ← Back to Landing Page
    </a>

    <h2 class="title is-2 mb-5">Advisors</h2>

    <div class="columns is-multiline">
      <!-- Loop through advisors dynamically -->
      {% for advisor in advisors_list %}
      <div class="column is-one-third">
        <a href="{% url 'manager:advisorDetail' advisor.advisorprofile.id %}" class="card-link-wrapper">
          <div class="card p-5 advisor-card">
            <div class="media">
              <div class="media-left">
                <figure class="image is-200x200">
                  <!-- Display image, use default if not found -->
                  <img src="{% if advisor.advisorprofile.image %}{{ advisor.advisorprofile.image.url }}{% else %}{% static 'default_profile.png' %}{% endif %}" alt=" {{ advisor.get_full_name }} " style="object-fit: contain; height: 200px; width: 200px;">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <!-- Display advisor name -->
                  <h3 class="title is-3 mb-3 advisor-name">{{ advisor.get_full_name }}</h3>
                  <p class="is-size-6 mt-2 advisor-email">
                      {{ advisor.advisorprofile.title }}
                  </p>
                  <p class="is-size-6 mt-2 advisor-email">
                      {{ advisor.email }}
                  </p>
                  <h5 class="is-size-6 mt-2 advisor-email">
                      {{ advisor.campus|upper }}
                  </h5>
                </div>
              </div>
            </div>
          </div>
        </a>
      </div>
      {% empty %}
      <p>No advisors available.</p>
      {% endfor %}
    </div>

{% endblock %}

project_manager/templates/project_manager/landingPage.html
{% extends "project_manager/base.html" %}
{% block content %}
{% load static %}
<section class="section" style="padding-top: 120px;">
  <div class="container has-text-centered">
      <h1 class="title is-3 mb-6">What would you like to do?</h1>

      <div class="columns is-centered is-variable is-8 is-multiline">
            <!-- Student View -->


<div class="column is-one-third">
  <div class="box has-text-centered">
    <a href="{% url 'manager:projectProposal' %}" class="landingbutton">
      <figure class="image is-128x128 is-inline-block mb-2">
        <img src="{% static 'create-project.png' %}" alt="Advisors Icon">
      </figure>
      <div class="is-size-5 has-text-weight-semibold">Create a Project</div>
    </a>
  </div>
</div>
<div class="column is-one-third">
  <div class="box has-text-centered">
    <a href="{% url 'manager:projectList' %}" class="landingbutton">
      <figure class="image is-128x128 is-inline-block mb-2">
        <img src="{% static 'view-projects.png' %}" alt="Advisors Icon">
      </figure>
      <div class="is-size-5 has-text-weight-semibold">View Projects</div>
    </a>
  </div>
</div>
<div class="column is-one-third">
  <div class="box has-text-centered">
    <a href="{% url 'manager:advisorList' %}" class="landingbutton">
      <figure class="image is-128x128 is-inline-block mb-2">
        <img src="{% static 'advisor-list.png' %}" alt="Advisors Icon">
      </figure>
      <div class="is-size-5 has-text-weight-semibold">Advisors</div>
    </a>
  </div>
</div>
      </div>
  </div>
</section>
{% endblock %}

project_manager/templates/project_manager/projectApplicationList.html
{% extends "project_manager/base.html" %}

{% block content %}
<h2>Applications for {{ applications.0.project.title }}</h2>
<ul>
	{% for application in applications %}
	<li>
   <h3 class="title is-3 ml-2 pt-6"><a href="{% url 'manager:applicationDetail' application.id %}">{{ application.applicant.get_full_name }}</a></h3>
		
	</li>
	{% empty %}
	<li>No applications yet.</li>
	{% endfor %}
</ul>
{% endblock %}

project_manager/templates/project_manager/projectDetailPage.html
{% extends "project_manager/base.html" %}

{% block content %}
    <div class="mt-6 mb-5">
      <a href="{% url 'manager:projectList' %}" class="button is-light mb-5">
        ← Back to Project List Page
      </a>
    </div>
    <!-- Project Title -->
    <h1 class="title is-2 mb-2">
      {{ project.title }}  <!-- Dynamically show project title -->
    </h1>

    <!-- Line under title -->
    <hr class="my-4">

    <!-- Project Description -->
    <div class="content mb-5">
      <p>
        {{ project.description }}  <!-- Dynamically show project description -->
      </p>
    </div>

    <hr class="my-5">

    <!-- Skills, Members, Advisor, Buttons -->
    <div class="columns is-variable is-8">

      <!-- Left Column (Skills) -->
      <div class="column is-4">
        <p class="has-text-weight-bold mb-2">Skills needed:</p>
        <ul>
          {% for skill in project.skills_required.all %}
            <li>{{ skill.name }}</li>
          {% empty %}
            <li>No skills required</li>
          {% endfor %}
        </ul>
      </div>

      <!-- Right Section: Members + Advisor + Buttons -->
      <div class="column is-8">
        <div class="columns is-multiline">

          <!-- Members Section -->
          <div class="column is-6">
            <p class="has-text-weight-bold mb-2">
              Members: <span class="has-text-weight-normal">{{ project.students.count }}/{{ project.member_limit }}</span>
            </p>
            <!-- List member names -->
            {% for member in project.members.all %}
              <p>{{ member.get_fullname }}</p>  <!-- Display each member's name -->
            {% empty %}
              <p>No members</p>
            {% endfor %}
          </div>

          <!-- Advisor Section -->
          <div class="column is-3">
            <p class="has-text-weight-bold mb-2">Advisor:</p>
            <p>
              {% if project.advisor %}
                {{ project.advisor.user.first_name }} {{ project.advisor.user.last_name }}  <!-- Dynamically show advisor name -->
              {% else %}
                N/A
              {% endif %}
            </p>
          </div>

          <!-- Buttons Section -->
          <div class="column is-3">
            <div class="is-flex is-flex-direction-column align-buttons">
              {% if project.created_by == request.user %}
              <button class="button is-orange half-width is-tall mb-3">
                <a href="{% url 'manager:projectApplications' project.id %}">View Applications</a>
              </button>
              <button class="button is-orange half-width is-tall mb-3">
                <a href="{% url 'manager:projectEdit' project.id %}">Edit Project</a>
              </button>
              {% else %}
                <button class="button is-orange half-width is-tall mb-3">Apply</button>
              {% endif %}

            </div>
          </div>

        </div>
      </div>

{% endblock %}

project_manager/templates/project_manager/projectEditPage.html
{% extends "project_manager/base.html" %}
{% block content %}
{{ form.non_field_errors }}
<section class="section">
  <div class="container">

    <!-- Back Button -->
    <a href="{% url 'manager:landingPage' %}" class="button is-light mb-5">
      ← Back to Landing Page
    </a>

    <!-- Form -->
    <form method="POST">
      {% csrf_token %}

      <!-- Project Title Input -->
      <div class="field">
        <div class="control pb-1">
          {{ form.title }}
        </div>
      </div>

      <!-- Project Description Textarea -->
      <div class="field">
        <div class="control">
          {{ form.description }}
        </div>
      </div>

      <div class="columns is-mobile">

        <!-- Skills Input -->
        <div class="column">
          <div class="field" style="max-width: 400px;">
            <label class="label label-special">Skills needed:</label>
            <div class="control">
              {{ form.skills_required }}
            </div>
          </div>
        </div>

        <!-- Members Dropdown -->
        <div class="column">
          <div class="field">
            <label class="label label-special" for="members">Members:</label>
            <div class="control">
              <div class="select is-custom">
                {{ form.member_limit }}
              </div>
            </div>
          </div>
        </div>

      </div>

      <!-- Submit Button -->
      <div class="button-right-align">
        <button type="submit" class="button is-orange is-medium" style="padding: 1rem 2rem;">
          Submit
        </button>
      </div>
      <div class="button-right-align">
      <a href="{% url 'manager:projectDelete' project.id %}" class="button is-danger">
        Delete Project
      </a>
      </div>
    </form>

  </div>
</section>
{% endblock %}

project_manager/templates/project_manager/projectListPage.html
{% extends "project_manager/base.html" %}

{% block content %}
    <a href="{% url 'manager:landingPage' %}" class="button is-light mb-5 mt-6 ">
      ← Back to Landing Page
    </a>
  {% if pending_projects_list %}
   <h3 class="title is-3 ml-2 pt-6">Projects</h3>
   <div class="select is-small ml-2">
    <select id="statusFilter">
     <option value="all">Filter by Status</option>
     <option value="active">Active</option>
     <option value="in_process">In Process</option>
     <option value="completed">Completed</option>
     <option value="archived">Archived</option>
     <option value="trash">Trash</option>
   </select>
   </div>
    <table class="table is-striped is-fullwidth is-hoverable is-hoverable ml-1 mr-5">
      <thead>
        <tr>
          <th>Members</th>
          <th>Author</th>
          <th>Title</th>
          <th>Created Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for project in pending_projects_list %}
          <tr>
            <td>{% if project.created_by.user_type == "student" or project.created_by.user_type == "advisor" %} 1 / {{ project.member_limit }}
              {% elif project.members.count >= 1 %}{{ project.members.count }} / {{ project.member_limit }} {% endif %}</td>
            <td>{{ project.created_by.get_full_name }}</td>
            <td>
              <a href="{% url 'manager:projectDetail' project.id %}">
                {{ project.title }}
              </a>
            </td>
            <td>{{ project.created_date }}</td>
            <td>
              {% if project.created_by == request.user %}
                <a href="{% url 'manager:projectDetail' project.id %}">View</a>
              {% else %}
                <a href="{% url 'manager:projectApplication' project.id %}">Apply</a>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p>No pending projects available.</p>
  {% endif %}
{% endblock %}

project_manager/templates/project_manager/projectProposalPage.html
{% extends "project_manager/base.html" %}
{% block content %}
{{ form.non_field_errors }}
<section class="section">
    <div class="container">

      <!-- Back Button -->
      <a href="{% url 'manager:landingPage' %}" class="button is-light mb-5">
        ← Back to Landing Page
      </a>

      <!-- Form -->
      <form action="{% url 'manager:projectProposal' %}" method="POST" >
        {% csrf_token %}

        <!-- Project Title Input -->
        <div class="field">
          <div class="control pb-1">
            {{ form.title }}
          </div>
        </div>

        <!-- Project Description Textarea -->
        <div class="field">
          <div class="control">
            {{ form.description }}
          </div>
        </div>

        <div class="columns is-mobile">

          <!-- Skills Input -->
          <div class="column">
            <div class="field" style="max-width: 400px;">
              <label class="label label-special">Skills needed:</label>
              <div class="control">
                {{ form.skills_required }}
              </div>
            </div>
          </div>

          <!-- Members Dropdown -->
          <div class="column">
            <div class="field">
              <label class="label label-special" for="members">Members:</label>
              <div class="control">
                <div class="select is-custom">
                 {{ form.member_limit }}
                </div>
              </div>
            </div>
          </div>

        </div>

        <!-- Submit Button -->
        <div class="button-right-align">
          <button type="submit" class="button is-orange is-medium" style="padding: 1rem 2rem;">
              Submit
          </button>
        </div>
      </form>

    </div>
  </section>
{% endblock %}